/**
 * Password reset tokens — api_design.docx §5.5: "Use a short-lived,
 * single-use reset token. Store only a hash of the reset token if
 * persisted." The raw token goes out in the email link; only its hash
 * (never reversible) is written to `users.passwordResetTokenHash`.
 *
 * SHA-256, not Argon2id: this token is already 256 bits of
 * `crypto.randomBytes` — high-entropy and generated by us, not a
 * human-memorized secret an attacker could dictionary-attack — so a fast
 * cryptographic hash is the correct tool, the same reasoning
 * db_design.docx applies to invitation `tokenHash`. Argon2id's deliberate
 * slowness exists to blunt guessing a low-entropy password; it buys
 * nothing here and would just make every reset-password request slower.
 */
import { randomBytes, createHash } from 'node:crypto';

const RESET_TOKEN_BYTES = 32;
export const RESET_TOKEN_TTL_MS = 60 * 60 * 1000; // 1 hour

export function generatePasswordResetToken(): string {
  return randomBytes(RESET_TOKEN_BYTES).toString('hex');
}

export function hashPasswordResetToken(rawToken: string): string {
  return createHash('sha256').update(rawToken).digest('hex');
}
