/**
 * Wedding-member invitation tokens — same reasoning as
 * modules/auth/auth.reset-token.ts's password-reset tokens: SHA-256, not
 * Argon2id, because the raw token is already 256 bits of
 * crypto.randomBytes (high-entropy, generated by us), not a low-entropy
 * secret an attacker could dictionary-attack. Only the hash is persisted
 * (invitations.model.ts's `tokenHash`); the raw token goes out once, in the
 * invitation email/link.
 */
import { randomBytes, createHash } from 'node:crypto';

const INVITATION_TOKEN_BYTES = 32;
export const INVITATION_TOKEN_TTL_MS = 7 * 24 * 60 * 60 * 1000; // 7 days

export function generateInvitationToken(): string {
  return randomBytes(INVITATION_TOKEN_BYTES).toString('hex');
}

export function hashInvitationToken(rawToken: string): string {
  return createHash('sha256').update(rawToken).digest('hex');
}
